// Automatically generated by astro-icon
// 38298b8cedb0c51bbc98a0d804029d7952bb96ba9d03f0a786f4afcb3ee1241d

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "circle"
		| "flask"
		| "goal"
		| "logo"
		| "mail"
		| "target"
		| "timeline";
}