// Automatically generated by astro-icon
// 5fd6e34eb36fd001f88d720e22203662dc254123a4fc8ec2d95f56e5a45073f2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "caret"
		| "circle"
		| "eye"
		| "flask"
		| "goal"
		| "logo"
		| "mail"
		| "people"
		| "scale"
		| "target"
		| "timeline";
}