// Automatically generated by astro-icon
// 43c58cef6cc141e7120192e3391bb96bbdc260b24499ee1d4072e3a42c4a764e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "circle"
		| "flask"
		| "logo"
		| "mail"
		| "timeline";
}